# Jekyll configuration for the blog directory

# Define custom posts collection
collections:
  blog_posts:
    output: true
    permalink: /blog/:title/   # You can set a custom permalink format for blog posts

# Base URL (adjust if your site is in a subfolder)
baseurl: ""  # If it's hosted at the root, leave it empty.

# Optional: Set the theme (if you want to use a default theme)
theme: minima
