url: "https://rhystic.study"
baseurl: "/blog"
theme: jekyll-theme-hacker
title: Rhystic Studios
description: Crystals Blog Posts

paginate: 5
paginate_path: "/blog/page:num/"

collections:
  blog_posts:
    output: true
    permalink: /blog/:title/
